// ─── Last-resort preview image ───────────────────────────────────────────────
//
// A 1200x630 PNG of the brand mark on the cream field, 2KB, embedded as base64.
//
// It exists because of a specific outage: a native module failed to load in the
// deployed bundle, the route module never evaluated, and every request returned
// a 500 with an empty body. Facebook reported only "could not be processed as
// an image", and every shared waitlist link lost its picture until it was
// found. Whatever goes wrong in the renderer, a scraper should still be handed
// a real image with real magic bytes rather than nothing at all.
//
// Deliberately not generated: generating it is the thing that can fail.

const FALLBACK_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAABLAAAAJ2CAMAAAB4notuAAABYlBMVEX79+/nxIbku3P69OnXmi379u3YmzDYmizXmSzYmy76" +
  "9er69OjYmzLnxYfkunD69ev269Xdp0j269box4z26tbanznqy5Tx3bvw3bnXnDHlvHTpyZDfrVbZnjfbpUX269fpyI/05cnY" +
  "nTHx3rzt0qLjunH26tTpyI7fq1Lao0Daoz/rzpnaoDjnwn/ZnTPv16zdqU7y37/x27XnxYbZnTXjum/16tPz5Mjdq0/Znzbe" +
  "qUzgsl/v167Ynzbfrlnx3Lfu1KferVTfrlbZnjXx3Lb05szeqk3kuXD69ezw3rr16dLw3Lfv27Tv2K7fr1n37Njbo0LbpUT6" +
  "8+jcpEPZoTvfr1ju1anfrFLgsFvqypPmvnnlvHX05sv16NDpyY/lvnjnwoD16dHgsV3bpkbmwoHcpkfu1ajv163ZnTLy4cHg" +
  "sV7qzJXpyI3kvXfjuW7nw4Ly4cLfsFrmwX705crjuG3t1KTQySgVAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAGC0lEQVR42u3d" +
  "53YTVxiG0ZEs6UjGveNesONOQif0QGghgfTee+/3nwtIWNjS+UZyvPclPD/etTSac6YoAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOtxMrp5eH5u8u7jYau4t354eWv105oQrQc+5fnLoykP6ltVmZ7lMH" +
  "6B31B+v76aluV6frGgE9YezsdnqGrcqYTkDXjeydTAfQqn6sFdBVF36ppQOqnR/RC+ia/qmBdAir4/40BLrkxpfpkEZnVAO6" +
  "YLjSTIf3Qb9yQNnG5lNbNje0A8r16HJq08Id9YAy3WylttVO6QeUZ6eZOtAcVxAoSyV1aFBDoBzvp45NqQiU4Ztm54PV9BwL" +
  "KMGjVsqgdUZJINrI5ZTFwoSWQKzh+ZTJLe+8A7H+SNl8pSYQ6UYz32A1nYQGAvWNpoy+dtsMEGc8ZbWsKBBlYyDvYK26gxSI" +
  "8lfK7J6mQIwLtdyDVXuoKhBiNmX3s6pAhMeN/IPV8r1CIMLZFMBFM0CA+lbEYG37ij2Q30wKsaYskN16zGDNKgvk1r8fM1jn" +
  "hrUFMnshBfleW6Do6WOEDhQCcX6PGqwvtAXyeuNk1GANuGQGyGslhXlZXSCr03GD9aq6QFbPxQ3WnLpAVkNxg1VVF8jq7bjB" +
  "ek1dIKsX4wbreXWBrN6MG6zX1QWymowbrLfUBbJqxA3WSXUBgwX4SegnIVB46A5QeK0BKLw46sVRoHA0B6Bw+BkoXC/jehmg" +
  "cIEfQOGKZOD/6L2owfpBWyCzn6IG6xNtgeKIfEj1N22BzPpvx+zVNZ+qB7KrxgzWrLJAdg9iBmtNWSC7+pOIvdquKwvkV4kY" +
  "rEFdgQCPA24dbY3pCkT4MP9gfaoqEGKjlnuvag9VBWKczz1YQ5oCQca+y7tXqxOaAsXRuMbP1X1AnL7RnHs16mIZINBMM99e" +
  "Naf1BCJ9lm+wflUTCDX8Uq69utWvJhBrKdNH6xf8QwiEu9PKcibnFSWBeO9kePDe/FtHoAxTnQ/WjyoC5Rh0qQxwZOx0dAy6" +
  "Oa4gUJ6bHTx5r53SDyjTmYV292rX/4NAyZbafIP03RHtgLLdr7TxekNzz/vtQDfMHPruhlHnnYEuGd7ZP9R9feN9mgFdM3Lv" +
  "wC841IacHgS6a2Jv4EBnB6ufawV03dLg1rPm6sngkk5AT6ivzZ57+lpdm13zPXqglzbr4tSV//ht2NqsTHvSDvSevj+vzq1f" +
  "v7Q42WhMLl66Xp27+pGxAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOvQRw" +
  "RBgswGABGCzg+A4WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABACf4BX4Zmcold+6gAAAAASUVORK5CYII=";

export const FALLBACK_PNG = Buffer.from(FALLBACK_PNG_BASE64, "base64");
